### ISSUE TITLE
Improvements to ColumnListItem - Workflows view

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/hyperdrive-trigger#13]
I have these ideas for the main workflow view. I think they would help usability a lot

## Ideas
1. Add pagination - there is a limit of 100 elements, extendable but still, pagination might be better
2. Add sorting and grouping capabilities - be able to sort by name and dates
3. Add search for workflow name - search could be only by name and would be enough

**Comment by kevinwallimann** [comment]
Should be fixed with #215
