### ISSUE TITLE
Add versioning

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/hyperdrive-trigger#14]
I think this is for any data manipulation and/or workflow setup one of the most important things. These previous versions should be mainly in the view mode. Just so people can somehow copy it back.

This task would consist of:
1. Add versions
2. Add the ability to see and choose previous versions
3. Add user name of the updater

**Comment by Zejnilovic** [comment]
If we add a user name to the edits, add the name of the person that changed the entity last to the table.

**Comment by kevinwallimann** [comment]
Done by #233
