### ISSUE TITLE
Sorted app job arguments

### ISSUE THREAD

**Issue by jozefbakus** [AbsaOSS/hyperdrive-trigger#167]
App jobs arguments in workflow should be order alphabetically by key.

**Comment by kevinwallimann** [comment]
I'd like to change the scope of this issue. The root problem for the frustrating user experience when adding app arguments is not necessarily absent sorting, but that the order of app args is not preserved, i.e. arguments are not simply appended at the end, but may end up anywhere in the list. This is the bug which should be fixed first.
I tried out sorting and I agree with you now that it's surprising behaviour
