### ISSUE TITLE
Add Runs button to action menu of a workflow

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/hyperdrive-trigger#21]
Many times people will only want to go to their runs when they see/view what is in them to see how is the workflow behaving.

For that reason, I would add a `Runs` button to a workflow action menu that would open `URL/#/WorkflowRuns/X` without the need to go to runs, search for your WF again and open it up.

**Main point:** We would go from 5 operations to 3
5 operations: Search for workflow, See what it is, Open Runs, Search for Workflow, Open its run
3 operations: Search for workflow, See what it is, Open its runs

**Comment by jozefbakus** [comment]
Story was written for old UI, but it is still valid for new ui. 
User should be able to got from workflow to pre-filtered runs page (filters applied:  workflow name and project name)

Implementor has to decide how to pass filters into runs page. (pass params in url[prefered], as a @Input)
