### ISSUE TITLE
Simplify ingestion jobs input

### ISSUE THREAD

**Issue by jozefbakus** [AbsaOSS/hyperdrive-trigger#236]
We should decide how to implement simplification of ingestion job creation.

**Comment by kevinwallimann** [comment]
- Add new entity `JobTemplate`
- Add new field `job_template` to `JobDefinition`

![image](https://user-images.githubusercontent.com/54136196/89418426-530d3d00-d730-11ea-965a-935145098192.png)

- `JobTemplate`s are resolved in `Executors.scala`, when `JobDefinition`s are mapped to `JobInstance`s
- To select job templates in the UI, a new rest endpoint is required to get available job templates. The selection of jobTypes will be replaced with the selection of job templates.

**Data Migration**
- Job Templates will be hard-coded to the DB for now. Create job templates for GenericSparkJob, GenericShellJob, HyperconfomranceJob, KafkaOffloadingJob
- Existing job definitions with job types Spark must be assigned the GenericSparkJob template, existing Shell jobs  must be assigend the GenericShellJob
