### ISSUE TITLE
Disable editing of workflow name and status

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/hyperdrive-trigger#24]
### Currently:
User can 
- create a workflow, give it a name and activate it immediately after creation
- activate the workflow using an action button on the workflow overview page
- rename and (de)activate the workflow in edit mode

### Proposal
Disallow user from activating or renaming the workflow. 

### Reason
If he renames it, it leads to hard to find relations and maybe even inconsistencies in the versioning later on.
If you want them to (de)activate it from the edit view you then why have the (de)activate button in the workflows view. Allow the checkbox isActive only on creation, not edit.

**Comment by jozefbakus** [comment]
Let's discuss it with Sasa

**Comment by kevinwallimann** [comment]
Won't implement this. If the user wants to rename the workflow, he/she could copy the workflow and give it a new name and delete the old one. By doing that, the edit history and runs history will be lost, which is worse than losing some correlation due to workflow renames
