### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by kevinwallimann** [AbsaOSS/hyperdrive-trigger#272]
When opening a workflow from the sidemenu, the opened project is collapsed again. I have the feeling this was not the case before. 

Click on workflow in sidemenu
![image](https://user-images.githubusercontent.com/54136196/89871458-b4f9f680-dbb7-11ea-9525-26207cce9128.png)

After clicking on workflow
![image](https://user-images.githubusercontent.com/54136196/89871565-e5da2b80-dbb7-11ea-806d-b4c26b132147.png)

**Comment by zakera786** [comment]
Thats interesting . I dont remember that happening before
