### ISSUE TITLE
Rename Absa-Kafka sensor

### ISSUE THREAD

**Issue by kevinwallimann** [AbsaOSS/hyperdrive-trigger#338]
![image](https://user-images.githubusercontent.com/54136196/96100973-3c742680-0ed5-11eb-89ca-1b5d7ef4c16c.png)

The name "Absa-Kafka" is not very descriptive. The difference to the Kafka-Sensor is that the match properties are predefined. That doesn't have to do anything with Absa. I would suggest "Kafka Ingestion Token" or "Kafka Predefined"

For simplicity, I would make the change only on the frontend.

What do you think @jozefbakus @senelesithole

**Comment by senelesithole** [comment]
Yes, you are right. The former gets my vote. How about changing "Kafka" to "Ursa Minor" too long?

**Comment by kevinwallimann** [comment]
Since this is still an open source project, I think we should leave it as "Kafka" (or make it configurable)

**Comment by kevinwallimann** [comment]
Other suggestions:
1. Rename Kafka -> Notification Topic
2. Rename Absa-Kafka to one of the following:
- Global Notification Topic
- Hyperdrive Notification Topic
- Managed Notification Topic

**Comment by jozefbakus** [comment]
1. I would leave Kafka. It says everything you need to know. Notification topic could be something else than Kafka. 
2. Absa-Kafka -> Kafka-token or something similar

**Comment by kevinwallimann** [comment]
1. Ok
2. Yes, the notification topic doesn't have to be the hyperdrive notification topic, can be any topic, sorry I confused that again. Looks like we reach consensus on "Kafka Token" or "Kafka Ingestion Token". I would prefer "Kafka Ingestion Token" because it's a bit more specific than just token and the field in the json is also named `ingestionToken`

**Comment by senelesithole** [comment]
Kafka Ingestion Token it is.
