### ISSUE TITLE
Failed to load hyperdriver/Component-preload.js

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/hyperdrive-trigger#5]
When I open the app I get `failed to load Javascript resource: hyperdriver/Component-preload.js -  sap.ui.ModuleSystem` and 

Rest call
```
Request URL: xxx/Component-preload.js
Request Method: GET
Status Code: 404 
```

**Comment by kevinwallimann** [comment]
Not an issue in new ui
