### ISSUE TITLE
Catch and log Slick exceptions

### ISSUE THREAD

**Issue by kevinwallimann** [AbsaOSS/hyperdrive-trigger#54]
Currently, exceptions thrown by Slick on DB operations (e.g. inserting `null` in a non-null column) are not caught and logged within the repositories and may thus easily be swallowed.

Exceptions could be caught like this:
```
db.run(action.asTry)
    .map {
      case Success(_) => (): Unit
      case Failure(ex) => logger.error("Error occured when inserting joined dag instances", ex)
    }
```

Less intrusive solutions are welcome

**Comment by kevinwallimann** [comment]
See `WorkflowRepository.scala` Slick exceptions are already caught e.g. for `insertWorkflow`, `updateWorkflow`

**Comment by jozefbakus** [comment]
Similar thing implemented in the notificaitons
