### ISSUE TITLE
Apache Livy investigation - submit spark jobs via Livy - for AWS

### ISSUE THREAD

**Issue by jozefbakus** [AbsaOSS/hyperdrive-trigger#541]
- Investigate Livy possibilities. 
- Investigate exactly once job deployment/execution. 
- How is batch id generated? 
- When are batches deleted?
- Can we upload local files via Livy? 
- How does impersonation works?
- Do we have to submit a job with a proxy user?
- Can we use a keytab to auth against Livy and run a job without keytab/proxy user?
- AWS Impersonation bug: https://github.com/absa-group/ursa-hadoop-to-cloud/issues/84

**Comment by kevinwallimann** [comment]
**How is batch id generated?**
https://github.com/apache/incubator-livy/blob/4d8a912699683b973eee76d4e91447d769a0cb0d/server/src/main/scala/org/apache/livy/sessions/SessionManager.scala#L90-L94

Ids are simply incremented based on an AtomicInteger. I.e. if Livy is restarted, it starts with 0 again. A HA setup of Livy should be possible, but if the whole EMR is shutdown, then it will start with 0 again.

**When are batches deleted?**
https://github.com/apache/incubator-livy/blob/master/server/src/main/scala/org/apache/livy/LivyConf.scala#L259
https://github.com/apache/incubator-livy/blob/master/server/src/main/scala/org/apache/livy/sessions/SessionManager.scala#L156-L180

Configurable, 1h by default

**Can we upload local files via Livy?**
Yes, see
https://github.com/apache/incubator-livy/blob/master/scala-api/src/main/scala/org/apache/livy/scalaapi/LivyScalaClient.scala#L127

**Can we use a keytab to auth against Livy and run a job without keytab/proxy user?**
We should be able to authenticate with keytab (works like that on-prem)

**Max sessions in Livy**
https://github.com/apache/incubator-livy/blob/master/server/src/main/scala/org/apache/livy/LivyConf.scala#L263
The default maximum sessions in Livy is 100. If there are too many sessions, the request is refused with a Bad Request. https://github.com/apache/incubator-livy/blob/master/server/src/main/scala/org/apache/livy/server/SessionServlet.scala#L131-L133
