### ISSUE TITLE
Investigate how spark-submit works

### ISSUE THREAD

**Issue by jozefbakus** [AbsaOSS/hyperdrive-trigger#559]
Investigate how spark-submit works.

**Comment by kevinwallimann** [comment]
The following explanations are mainly to understand the submission of yarn jobs in cluster mode.

- [spark-submit](https://github.com/apache/spark/blob/v3.2.0/bin/spark-submit) script, launches java process using script [spark-class](https://github.com/apache/spark/blob/v3.2.0/bin/spark-class) with main class [org.apache.spark.deploy.SparkSubmit](https://github.com/apache/spark/blob/v3.2.0/core/src/main/scala/org/apache/spark/deploy/SparkSubmit.scala)
  - `spark-class`
    - finds `java`
    - executes `$SPARK_HOME/conf/spark-env.sh` through `$SPARK_HOME/bin/load-spark-env.sh`
    - starts java process
    - [org.apache.spark.launcher.Main](https://github.com/apache/spark/blob/v3.2.0/launcher/src/main/java/org/apache/spark/launcher/Main.java) builds the command to be executed by `spark-class`, e.g. something like
```
/usr/lib/jvm/java-1.8.0-openjdk/jre/bin/java -cp /opt/spark/conf/:/opt/spark/jars/*:/opt/hadoop/ \
-Dscala.usejavacp=true org.apache.spark.deploy.SparkSubmit --master yarn --deploy-mode cluster \
--conf spark.executor.memory=1g --conf spark.driver.memory=1g  \
--class za.co.absa.hyperdrive.driver.drivers.CommandLineIngestionDriver --name Hyperdrive \
--jars spark-jobs-current.jar hyperdrive-release-latest.jar arg1 arg2
```
  - `SparkSubmit`
    - `main` -> `doSubmit` -> `submit` -> `doRunMain` -> `runMain` -> `prepareSubmitEnvironment`
    - [prepareSubmitEnvironment](https://github.com/apache/spark/blob/v3.2.0/core/src/main/scala/org/apache/spark/deploy/SparkSubmit.scala#L220) returns among others the main class to execute.
      - and the config is also looked up here. (TODO: Reference)
      - Also, login with keytab and principal is done here. https://github.com/apache/spark/blob/v3.2.0/core/src/main/scala/org/apache/spark/deploy/SparkSubmit.scala#L359
      - Return the Yarn Client main class, which is [org.apache.spark.deploy.yarn.YarnClusterApplication](https://github.com/apache/spark/blob/v3.2.0/resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/Client.scala#L1666)

  - `org.apache.spark.deploy.yarn.Client`
    - `YarnClusterApplication.start` -> `Client.run` -> `Client.submitApplication`
    - The upload of jars happens here: https://github.com/apache/spark/blob/v3.2.0/resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/Client.scala#L391
    - [submitApplication](https://github.com/apache/spark/blob/v3.2.0/resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/Client.scala#L391) calls `yarnClient.createApplication()` and then `yarnClient.submitApplication(ApplicationSubmissionContext)`

- There are two implementations of [AbstractLauncher](https://github.com/apache/spark/blob/v3.2.0/launcher/src/main/java/org/apache/spark/launcher/AbstractLauncher.java), which can be used to programmatically launch a spark job with the method [startApplication](https://github.com/apache/spark/blob/v3.2.0/launcher/src/main/java/org/apache/spark/launcher/AbstractLauncher.java#L274)
  - [SparkLauncher](https://github.com/apache/spark/blob/v3.2.0/launcher/src/main/java/org/apache/spark/launcher/SparkLauncher.java) creates a `java.lang.Process` that executes the `spark-submit` script.
  - [InProcessLauncher](https://github.com/apache/spark/blob/v3.2.0/launcher/src/main/java/org/apache/spark/launcher/InProcessLauncher.java) calls [org.apache.spark.deploy.InProcessSparkSubmit.main()](https://github.com/apache/spark/blob/v3.2.0/core/src/main/scala/org/apache/spark/deploy/SparkSubmit.scala#L982) directly within a thread (using `new Thread()`)
  - Both `SparkLauncher` and `InProcessLauncher` start a static instance of `LauncherServer` which is used to keep track of the launched spark jobs. The `LauncherServer` is not used when submitting an application through `spark-submit`

## Questions
- Is it really necessary for `spark-submit` to have the full `$SPARK_HOME` or are only specific files required?
