### ISSUE TITLE
Airflow Deferrable Operator YARN Status update

### ISSUE THREAD

**Issue by kevinwallimann** [AbsaOSS/hyperdrive-trigger#652]

**Comment by jozefbakus** [comment]
https://github.com/jozefbakus/airflow-hyperdrive
Call rest api in trigger while job is running.
My suggestion: 
- User has to set unique id per job
- Custom spark operator will first check yarn for running job with specified id 
> - If job is running in yarn defer and keep checking 
> - If job is not running in yarn, do submit and defer
