### ISSUE TITLE
Investigate deterministic execution plan 

### ISSUE THREAD

**Issue by jozefbakus** [AbsaOSS/hyperdrive-trigger#675]
Abris generates uiid for each microbatch.

**Comment by kevinwallimann** [comment]
It's not Abris, but Hyperdrive-Ingestor which creates the UUID's as column names. See https://github.com/AbsaOSS/hyperdrive/blob/v4.6.0/ingestor-default/src/main/scala/za/co/absa/hyperdrive/ingestor/implementation/transformer/avro/confluent/ConfluentAvroDecodingTransformer.scala#L51

Will be resolved here: https://github.com/AbsaOSS/hyperdrive/issues/265
