### ISSUE TITLE
Curly brace is lost from workflow app properties

### ISSUE THREAD

**Issue by kevinwallimann** [AbsaOSS/hyperdrive-trigger#677]
# Description
Add this app argument in a workflow on Hyperdrive-Trigger

`reader.option.startingOffsets={"topic1":{"0":132919595}}`

In hyperdrive-ingestor, this error occurs:

Caused by: java.lang.IllegalArgumentException: Expected e.g. {"topicA":{"0":23,"1":-1},"topicB":{"0":-2}}, got {"topic1":{"0":132919595}

Notice the missing closing brace at the end

The workaround is to add a space, like this

`reader.option.startingOffsets={"topic1":{"0":132919595} }`

In the first attempt, this issue could not be reproduced locally using the ingestor alone (neither using PropertiesIngestionDriver nor CommandLineIngestionDriver), without the trigger. So it seems it is an issue with the trigger.

**Comment by jozefbakus** [comment]
I've identified issue:
https://stackoverflow.com/questions/43040793/scala-via-spark-with-yarn-curly-brackets-string-missing
https://issues.apache.org/jira/browse/SPARK-17814
