### ISSUE TITLE
E-Mail notifications not sent

### ISSUE THREAD

**Issue by kevinwallimann** [AbsaOSS/hyperdrive-trigger#699]
It seems that when many jobs are failing, not all of the notification emails were received.

It is not clear, whether the notifications were not sent, or whether the notifications were not relayed or even considered spam.

**Comment by jozefbakus** [comment]
27.Jun - Failed jobs during restart did not send notifications
28.Jun - Failed jobs during restart did not send notifications
29.Jun - Failed jobs during restart did not send notifications
30.Jun - Failed jobs during restart did not send notifications
