### ISSUE TITLE
If no update was done / workflow just created set update time to creation time

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/hyperdrive-trigger#7]
This is more of an UI/UX thing. Not a bug.

From how all the other applications work, users are accustomed (imho) to the update time being the creation time if no update was done and workflow just created. Empty space looks more like information missing.

![image](https://user-images.githubusercontent.com/17467768/64518490-8feb6c80-d2f2-11e9-96c8-6cce08063941.png)

**Comment by kevinwallimann** [comment]
Creation / Update time not shown anymore in the new ui. Might be part of versioning in the future
