### ISSUE TITLE
Add timeout for MailSender

### ISSUE THREAD

**Issue by kevinwallimann** [AbsaOSS/hyperdrive-trigger#730]
Currently, the health page often takes more than 60s to load, because the mail health indicator has an infinite timeout to connect to the mail server. This is bad for a monitoring service, which might require a lower max load time of the health page.

Also, for the application itself, it doesn't make a lot of sense to wait infinitely for the mail server to come back up.

To limit the timeout, the following application properties should be set:

**Application properties**
```
spring.mail.properties[mail.smtp.connectiontimeout]=5000
spring.mail.properties[mail.smtp.timeout]=5000
spring.mail.properties[mail.smtp.writetimeout]=5000
```

See https://docs.spring.io/spring-boot/docs/2.6.x/reference/html/io.html#io.email

**Comment by jozefbakus** [comment]
Done
