### ISSUE TITLE
Remove testing properties for hyperdrive executor

### ISSUE THREAD

**Issue by kevinwallimann** [AbsaOSS/hyperdrive-trigger#743]
In v0.5.12, testing properties were introduced for the hyperdrive executor. Since the hyperdrive executor has proven to be reliable, they can be removed.

The following application property can be removed (and replaced by `true`): `executors.enable.hyperdrive.executor`

The method `useHyperExecutor` in `Executors.scala` can be removed (and replaced by `true`)

**Data migration**
In existing job templates, the application config `useHyperdriveExecutor=true` can be removed. Since it only concerns job templates, and keeping the application config will not break any workflows, this data migration can be done manually.

**Comment by jozefbakus** [comment]
Implemented. Remove `useHyperdriveExecutor` during deployment !
