### ISSUE TITLE
Update Angular and clarity versions to 14

### ISSUE THREAD

**Issue by kevinwallimann** [AbsaOSS/hyperdrive-trigger#751]
Upgrade Angular to version 14 (major)

Also upgrade clarity, and ngrx.

Currently, clarity version 14 has not been published yet, so this issue is on hold

**Comment by jozefbakus** [comment]
https://github.com/vmware-clarity/ng-clarity/commit/0fea6c65fbd456024f065d0f5f341f134188fe4e
