### ISSUE TITLE
What information about the topics can be read from AdminClient

### ISSUE THREAD

**Issue by kevinwallimann** [AbsaOSS/hyperdrive-trigger#774]
## Question
What information about the topics can be read from AdminClient?

## Context / Motivation / Practical application
Using a specific service user for authentication

E.g. listing topics, read / write permissions

## Existing information
Links to blogs, docs, stackoverflow, colleagues' opinions etc.

## Experiments / Observations [Optional]
If needed, experiments can be tasks of their own

**Comment by jozefbakus** [comment]
Tried 3 methods 
AdminClient.describeAcls(...) -  Needs special authorization
AdminClient.describeTopics(...) - Not available or needs special authorization
Producer/Consumer.partitionsFor(...) - This does not work. Producers returns correct result even we have no auth to do it
